### ISSUE TITLE
ld: cannot open crt0.o: No such file or directory

### ISSUE THREAD

**Issue by sebastianbergmann** [cahirwpz/amigaos-cross-toolchain#12]
Let me start with a big "Thank you!" for providing this toolchain. I recently dusted off my Amiga 1200 and now want to get my feet wet with cross-compiling for AmigaOS.

I made a fresh installation of Fedora 21 32bit in a virtual machine and followed the instructions in `README.md` (see https://github.com/cahirwpz/m68k-amigaos-toolchain/pull/11 for what was missing from it for me).

I then used the following "Hello world!" example code to test the cross-compiling toolchain ...

```c
#include <stdio.h>
int main()
{
    printf("Hello World!\n");
    return(0);
}
```
... with this command to invoke the cross-compiler

    $ m68k-amigaos-gcc hello.c -o hello
    /usr/local/m68k-amigaos/m68k-amigaos/bin/ld: cannot open crt0.o: No such file or directory
    collect2: ld returned 1 exit status

What am I missing? Compiling with `-noixemul` works:

    $ m68k-amigaos-gcc hello.c -o hello -noixemul

The binary generated by the command above executes properly on my Amiga 1200 with AmigaOS 3.9.

**Comment by cahirwpz** [comment]
You need to use `-noixemul` switch during linking stage, otherwise the toolchain will try to use ixemul startup routine which is not available.

```
$ m68k-amigaos-gcc -noixemul hello.c -o hello
```
