### ISSUE TITLE
missing utilities

### ISSUE THREAD

**Issue by stu** [cahirwpz/amigaos-cross-toolchain#13]
I did the build, which went with no errors. but I cant run the SDK install because its missing pushd/popd/lha 

*edit* to add some info;

    [$]> ./install-sdk.sh --prefix=/opt/m68k-amigaos ahi cgx mui
    Installing 'ahi'...
    mktemp: too few X's in template ‘ahi’
    ./install-sdk.sh: line 54: pushd: no other directory
    ./install-sdk.sh: line 58: lha: command not found

**Comment by cahirwpz** [comment]
I'm working to rewrite the whole script into Python.

As a temporary fix you can:

* add `.build-m68k/host/bin` to your PATH (for lha) before calling the script
* modify line 52 to: **local tmp=\`mktemp -d -t "${name}.XXX"\`**

**Comment by stu** [comment]
I had to modify LHA switches from -xgq to -xq, lhasa has no 'g'.

betterstring upgraded to 2.9, mcc texteditor, thebar, nlist all upgraded too

cgx throws a permission denied but that looks like a fault on aminet

**Comment by stu** [comment]
i was going to make patch but if your rewriting in python, Ill leave it. python also has that nice lha extension that fsuae also uses.  cheers mate!

**Comment by cahirwpz** [comment]
> I had to modify LHA switches from -xgq to -xq, lhasa has no 'g'. 

Yup. I know about it. `install-sdk.sh` will be integrated with `toolchain-m68k` script and will use unpacking routines from `common.py`.

> betterstring upgraded to 2.9, mcc texteditor, thebar, nlist all upgraded too

I'll take the patches.

> python also has that nice lha extension that fsuae also uses.

Can you provide a link?

BTW. I'll leave the issue open until I rewrite the whole script to Python. Eventually I'll ask you to test it.

**Comment by FrodeSolheim** [comment]
https://github.com/FrodeSolheim/python-lhafile :D

**Comment by stu** [comment]
http://fengestad.no/python-lhafile/

**Comment by stu** [comment]
i sent a pull request for the updates in two commits. you can ignore the install-sdk patch if you want

**Comment by cahirwpz** [comment]
The toolchain build script is ready for testing.
