### ISSUE TITLE
new install script fails

### ISSUE THREAD

**Issue by stu** [cahirwpz/amigaos-cross-toolchain#15]
INFO: preparing files for "vclib"
    DEBUG: enter directory ".build-m68k/tmp/tmpbppKN1"
    INFO: extract files from ".build-m68k/archives/vclib.lha"
    DEBUG: extract "vbcc_target_m68k-amigaos.info"
    Traceback (most recent call last):
      File "./toolchain-m68k", line 605, in <module>
        globals()[action].__call__(*args.args)
      File "./toolchain-m68k", line 285, in build
        unpack('vclib', top_dir='vbcc_target_m68k-amigaos')
      File "/home/sgeorge/nas/outside/amigaos-cross-toolchain/common.py", line 37, in wrapper
        return fn(*args, **kwargs)
      File "/home/sgeorge/nas/outside/amigaos-cross-toolchain/common.py", line 349, in wrapper
        fn(*args, **kwargs)
      File "/home/sgeorge/nas/outside/amigaos-cross-toolchain/common.py", line 405, in unpack
        unarc(src)
      File "/home/sgeorge/nas/outside/amigaos-cross-toolchain/common.py", line 37, in wrapper
        return fn(*args, **kwargs)
      File "/home/sgeorge/nas/outside/amigaos-cross-toolchain/common.py", line 278, in unarc
        f.write(arc.read(item.filename))
      File "/usr/lib/python2.7/dist-packages/lhafile/lhafile.py", line 344, in read
        fin = BytesOrStringIO(self.fp.read(info.compress_size))
    NameError: global name 'BytesOrStringIO' is not defined

looks like an issue in lhafile which is strange, and I dont know enough about python. BytesOrStringIO is an import from BytesIO. Python has a bytesio class so I dont know whats going on...

**Comment by cahirwpz** [comment]
I've already fixed that error. Please invoke `toolchain-m68k clean` and then remove `.build-m68k/archives/python-lhafile` directory.

**Comment by stu** [comment]
File "/usr/lib/python2.7/dist-packages/lhafile/lhafile.py", line 344, in read
    fin = BytesOrStringIO(self.fp.read(info.compress_size))

except that says /usr/lib, I did not run this as sudo so its not using the python-lhafile in your build script, its using my global system copy that I installed for fs-uae, not the one inside your script.

script failed in same place.

**Comment by cahirwpz** [comment]
Hi,

On Thu, Sep 10, 2015 at 2:22 PM, Stu <notifications@github.com> wrote:

> File "/usr/lib/python2.7/dist-packages/lhafile/lhafile.py", line 344, in read
> fin = BytesOrStringIO(self.fp.read(info.compress_size))
>
> except that says /usr/lib, I did not run this as sudo so its not using the
> python-lhafile in your build script, its using my global system copy that I
> installed for fs-uae, not the one inside your script.
>
> script failed in same place.
>

Please poke Frode to fix it. I sent him a fix the other day and he hasn't
responded yet. In the meantime you may fix your local copy python-lhafile
in exactly the same way I did:
https://github.com/cahirwpz/python-lhafile/commit/a048564057525c57042b3978f1a803201e57f4dc

It seems that your python installation somehow prefers local installation
of python-lhafile instead of mine. I'll investigate that at home.

Thanks for reporting that. I didn't consider problems with PYTHONPATH
variable.

-- 
Kind regards
Krystian Bacławski

**Comment by stu** [comment]
i did the local fix, build continued and completed.

I did install-sdk ahi cgx mui mcc_betterstring mcc_nlist mcc_texteditor mcc_thebar mmu, also without any errors.

so it looks like just the fix to python lhafile is the show stopper right now

**Comment by cahirwpz** [comment]
Please compile sources from `examples` directory to test the toolchain.

**Comment by stu** [comment]
Running make in examples built with no errors using the new install.

**Comment by FrodeSolheim** [comment]
python-lhafile updated to 0.2.1 (in repo and on http://fengestad.no/python-lhafile/) :)

**Comment by cahirwpz** [comment]
@FrodeSolheim Thanks!
