### ISSUE TITLE
./toolchain-ppc build doesnt work

### ISSUE THREAD

**Issue by Peabrain** [cahirwpz/amigaos-cross-toolchain#17]
DEBUG: makedir "ppc-amigaos"
Traceback (most recent call last):
  File "./toolchain-ppc", line 241, in <module>
    globals()[action].__call__(*args.args)
AttributeError: 'Namespace' object has no attribute 'args'

**Comment by cahirwpz** [comment]
How to reproduce this bug?

**Comment by Peabrain** [comment]
hello,
i only try to compile the newest version of git.
best regards

Date: Mon, 18 Jan 2016 02:19:48 -0800

**Comment by cahirwpz** [comment]
Unfortunately that kind of answer doesn't help me at all. Everything works fine on my system.
