### ISSUE TITLE
Intermittent errors on Cygwin

### ISSUE THREAD

**Issue by leffmann** [cahirwpz/amigaos-cross-toolchain#22]
```OSError: [Errno 11] Resource temporarily unavailable```

I'm suddenly getting a lot of these. They come and go as I rerun the build script. Just putting it up here in case someone can figure it out. Full error log is [here](https://gist.github.com/leffmann/6a3088e639b371e3bc90#file-gistfile1-txt).

**Comment by cahirwpz** [comment]
```
python2.7 632 child_info_fork::abort: address space needed by 'lzhlib.dll' (0x1A0000) is already occupied
File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
  self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable
```

This looks like a problem with Cygwin installation - seems like they're aware of it. There's a tool called [rebaseall](http://cygwin.wikia.com/wiki/Rebaseall) that supposedly fixes the problem. Could you try it out?

**Comment by leffmann** [comment]
Thanks that was it. It doesn't fix it, but obviously it's entirely the fault of Windows, so I'll just close.
