### ISSUE TITLE
gcc-2.95.3: clib2 support

### ISSUE THREAD

**Issue by jens-maus** [cahirwpz/amigaos-cross-toolchain#32]
While building the m68k gcc-2.95.3 toolchain defaults to libnix/ixemul building only, it should be noted that it can be quite easily tuned to also compile with clib2 (https://github.com/adtools/clib2) which is also available for os3-m68k and which is already widely used for compiling certain OS3 projects (YAM, MUI, AmiSSL, etc.).

Thus, it would be great if there would be an option to also build the toolchain with clib2 compatibility so that we don't have to manually tune the build environment afterwards to integrate clib2 support.

**Comment by cahirwpz** [comment]
Can you describe how to install compiled clib2 over current installation of amigaos-cross-toolchain?

In long term I'd prefer to modify gcc specs file to work for compilation against clib2 in similar fashion as with AmigaOS4 toolchain (-mclib2 option).

**Comment by jens-maus** [comment]
Unfortunately I haven't documented these changes. I applied them successively after having created the cross compiler with your methods. However, please grab the full archive of my /opt/m68k-amigaos directory from the following URL and see if you can use it or diff the changes against your cross compiler environment:

https://cloud.light-speed.de/index.php/s/pO5Ch8nHxDXh4Jq

Please note that together with the clib2 modifications this also comes with binutils-2.14 with patches to fix baserel support. These patches are still, however, in the old SVN repository of the adtools project on sf.net.

Also note that this exactly the cross compiler we are currently using to build the nightly builds of yam (http://yam.ch) as well as AmiSSLv4 and also MUI4 for OS3.

**Comment by cahirwpz** [comment]
Should work with `-mcrt=clib2` instead of `-noixemul`. Please test it.

**Comment by cahirwpz** [comment]
Should work with `-mcrt=clib2` in place of `-noixemul`. @jens-maus Please test it.

**Comment by cahirwpz** [comment]
Should work with `-mcrt=clib2`. Have a look at [examples/Makefile](https://github.com/cahirwpz/amigaos-cross-toolchain/blob/master/examples/Makefile#L18).

@jens-maus Could you please verify it?

**Comment by jens-maus** [comment]
I just verified that clib2 support works now. Thanks for having implemented it so smoothly! Great work.
