### ISSUE TITLE
Unable to compile toolchain on Mac OS X El Capitan

### ISSUE THREAD

**Issue by MBeijer** [cahirwpz/amigaos-cross-toolchain#33]
I am unable to compile the toolchain on Mac OS X El Capitan. I was able to just a couple of weeks ago, but now it breaks when trying to compile the dummy for some reason! It could be related to a Xcode upgrade I installed recently.

`cp xgcc gcc-cross
/tmp/amigaos-cross-toolchain/.build-m68k/build/gcc-2.95.3/gcc/xgcc -B/tmp/amigaos-cross-toolchain/.build-m68k/build/gcc-2.95.3/gcc/ -B/usr/local/amiga/m68k-amigaos/m68k-amigaos/bin/ -I/usr/local/amiga/m68k-amigaos/m68k-amigaos/include -dumpspecs > tmp-specs
mv tmp-specs specs
touch stmp-headers
echo "void __foo () {}" > dummy.c
/tmp/amigaos-cross-toolchain/.build-m68k/build/gcc-2.95.3/gcc/xgcc -B/tmp/amigaos-cross-toolchain/.build-m68k/build/gcc-2.95.3/gcc/ -B/usr/local/amiga/m68k-amigaos/m68k-amigaos/bin/ -I/usr/local/amiga/m68k-amigaos/m68k-amigaos/include -DCROSS_COMPILE -DIN_GCC     -g -I./include  -c dummy.c
m68k-amigaos-ar rc libgcc1.null dummy.o
make[1]: *** [libgcc1.null] Abort trap: 6
make[1]: *** Deleting file `libgcc1.null'
make: *** [all-gcc] Error 2
ERROR: command "make all-gcc CFLAGS_FOR_TARGET=-noixemul MAKEINFO=makeinfo" failed with 2`

clang version:
`$ clang -v
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by cahirwpz** [comment]
I need a full compilation log attached as a file. Remember to capture both **stdout** and **stderr**. Please start whole the from scratch.

Unfortunately, I'm not going to upgrade my OS to El Capitan (got Intel HD3000), which makes reproducing the issue quite difficult.

**Comment by MBeijer** [comment]
Alright, I'll give you all that info as soon as I got time!

**Comment by cahirwpz** [comment]
There were some changes to repo lately. Can you recheck if build still fails. Remember to do whole process from scratch.

**Comment by MBeijer** [comment]
Will do as soon as I'm back home from vacation.

**Comment by OliverUrbann** [comment]
Have the same problem (fresh clone today). 
[build.log.zip](https://github.com/cahirwpz/amigaos-cross-toolchain/files/254904/build.log.zip)

**Comment by cahirwpz** [comment]
Great! That supports my suspicion that new Clang is to blame. I removed requirement for compiler to support gnu89 standard. Please check again with the most recent XCode.

**Comment by OliverUrbann** [comment]
Unfortunately same problem.

**Comment by cahirwpz** [comment]
I have no methods of reproducing this problem on my machine, as such I'm unable to fix it.

**Comment by cahirwpz** [comment]
After recent update to Ubuntu 16.04 I encountered some bugs. One of them emerged in a similar context as described above. Please build the toolchain from scratch to check if my recent changes fixed the issue under MacOSX 10.11.

**Comment by cmsj** [comment]
I have successfully built the toolchain on 10.11 with current Xcode
