### ISSUE TITLE
issue in installing warp3d sdk

### ISSUE THREAD

**Issue by sezero** [cahirwpz/amigaos-cross-toolchain#35]
After successfully completing the build command, I do:
./toolchain-m68k --prefix=/home/me/xx install-sdk warp3d
It fails like this:
[code]
INFO: adding ".build-m68k/host/lib/python2.7/site-packages" to python site dirs
DEBUG: enter directory ".build-m68k/archives"
INFO: download: Warp3DDev-4.2a.lha (size: 336203)
......
DEBUG: enter directory ".build-m68k/sources/Warp3DDev-4.2a"
DEBUG: copy ".build-m68k/sources/Warp3DDev-4.2a/Warp3D_Devel/Docs/Warp3D.doc" to "../../xx/doc/Warp3D.doc"
DEBUG: copy ".build-m68k/sources/Warp3DDev-4.2a/Warp3D_Devel/Docs/Warp3D.guide" to "../../xx/guide/Warp3D.guide"
DEBUG: copy ".build-m68k/sources/Warp3DDev-4.2a/Warp3D_Devel/Docs/Warp3D_Devel.guide" to "../../xx/guide/Warp3D_Devel.guide"
DEBUG: copy ".build-m68k/sources/Warp3DDev-4.2a/Warp3D_Devel/Include/clib/Warp3D_protos.h" to "../../xx/os-include/clib/Warp3D_protos.h"
DEBUG: copy ".build-m68k/sources/Warp3DDev-4.2a/Warp3D_Devel/Include/fd/Warp3D.fd" to "../../xx/os-lib/fd/Warp3D_lib.fd"
DEBUG: makedir "../../xx/os-include/Warp3D"
DEBUG: copy ".build-m68k/sources/Warp3DDev-4.2a/Warp3D_Devel/Include/Warp3D/Warp3D.h" to "../../xx/os-include/Warp3D/Warp3D.h"
INFO: fd2sfd: "Warp3D_Devel/Include/fd/Warp3D_lib.fd" "Warp3D_Devel/Include/clib/Warp3D_protos.h" -> "Warp3D_lib.sfd"
DEBUG: execute "fd2sfd -o Warp3D_lib.sfd Warp3D_Devel/Include/fd/Warp3D_lib.fd Warp3D_Devel/Include/clib/Warp3D_protos.h"
Couldn't open file 'Warp3D_Devel/Include/fd/Warp3D_lib.fd'.
ERROR: command "fd2sfd -o Warp3D_lib.sfd Warp3D_Devel/Include/fd/Warp3D_lib.fd Warp3D_Devel/Include/clib/Warp3D_protos.h" failed with 1
[/code]

I then go into .build-m68k/sources/ and manually copy Warp3D.fd and Warp3D_lib.fd
and reissue the same command, then it succeeds.

Is it something wrong at my end, or is it a glitch with the python scripts?

BTW, you should use 4.2 version instead of 4.0, i.e. warp3d.sdk should change like:
Version: 4.2
Url: http://aminet.net/dev/misc/Warp3DDev-4.2a.lha

**Comment by cahirwpz** [comment]
It should work now. Please check it.

**Comment by sezero** [comment]
No failures anymore, thanks. However, the sfd is now installed as Warp3D.sfd
instead of Warp3D_lib.sfd under os-lib/

**Comment by cahirwpz** [comment]
Ok. I'll fix it.

**Comment by sezero** [comment]
There is a typo in toolchain-m68k at line 475: fd.endswith('_lib') must be changed to
fd.endswith('_lib.fd')
