### ISSUE TITLE
file:// or some equivalent of url support

### ISSUE THREAD

**Issue by sezero** [cahirwpz/amigaos-cross-toolchain#37]
I'd like to use local hard-disk-stored source files in some cases.  (My particular case is that I intend to use the gcc-2.95.4-prerelease version.) For that, support for file:///home/me/xxx.tar.gz type URLs, or some equivalent of it, would be very welcome.

**Comment by cahirwpz** [comment]
gcc-2.95-4-prerelease? Is there something I should know about?

**Comment by sezero** [comment]
>  gcc-2.95-4-prerelease? Is there something I should know about?

It is gcc-2_95-branch really. Some distros used it back in the day,
such as PLD which I rebased your amiga patches against their source
rpm gcc-2.95.4-0.20010823.3.src.rpm:
http://ftp.pld-linux.org/dists/1.1/PLD/SRPMS/SRPMS/gcc-2.95.4-0.20010823.3.src.rpm

**Comment by sezero** [comment]
Thanks for the implementation.  However, I think "copytree" at line 387 of common.py
needs changing to a simple "copy", otherwise it treats file:///home/myself/gcc-2.95.4.tar.gz
as a directory and the fails later.
