### ISSUE TITLE
libdebug.a

### ISSUE THREAD

**Issue by sezero** [cahirwpz/amigaos-cross-toolchain#39]
libdebug.a (<toolchain>/lib/libdebug.a) would be a good addition to m68k toolchain.
Source and binary rpms: https://sourceforge.net/projects/arp2/files/gg-libdebug/

**Comment by cahirwpz** [comment]
Seems like it should work. Please test it.

**Comment by sezero** [comment]
It works, thanks.

Although, with the latest changes, the following happens when I try
to compile uhexen2 (uhexen2.sf.net) svn for m68k-amigaos:
In file included from /home/me/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/sys/param.h:88,
                 from ../../common/q_stdinc.h:38,
                 from quakeinc.h:29,
                 from quakedef.h:226,
                 from ../h2shared/draw.c:26:
/home/me/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/machine/limits.h:44: warning: `SCHAR_MIN' redefined
/home/me/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/include/limits.h:19: warning: this is the location of the previous definition
... which did not happen before.

**Comment by cahirwpz** [comment]
Could you write minimal testcase for this issue so I can easily reproduce it locally?

**Comment by sezero** [comment]
Sorry that I was lazy. it is as simple as:
```
#include <limits.h>
#include <sys/param.h>
```
It seems like commit 3649955 broke it: since that commit abandoned sys-includes,
gcc didn't think that there is a system-provided limits.h when it was generating its on
limits.h.  If I add a symlink for it it takes care of it, like:
diff --git a/toolchain-m68k b/toolchain-m68k
```
index ea4fea2..2f2da73 100755
--- a/toolchain-m68k
+++ b/toolchain-m68k
@@ -94,6 +94,7 @@ def headers_install():
   info('installing ixemul header files')
 
   copytree('{sources}/{ixemul}/include', '{target}/m68k-amigaos/include')
+  symlink('{target}/m68k-amigaos/include','{target}/m68k-amigaos/sys-include')
 
 
 @recipe('tools-install')

```
