### ISSUE TITLE
iostream example crashes

### ISSUE THREAD

**Issue by OliverUrbann** [cahirwpz/amigaos-cross-toolchain#42]
"make hello-iostream" works and builds hello-iostream. However, it crashes on start with 80000008. It seems that an std cout does not work. Other things from std seems to work. Additionally it works if I just compile anything with cout and link it using the native g++ under OS 3. So, it is something related to the linker when cout is used.

Additionally, executed in the examples folder:

$ make
m68k-amigaos-gcc -noixemul -s -fbaserel  -Os -Wall -fomit-frame-pointer -m68000 -msmall-code    hello-ks13.c  -lnix13 -o hello-ks13
collect2: ld terminated with signal 6 [Abort trap: 6], core dumped
pc relative relocation out of range in section.text. Relocation was to symbol __edata
make: *** [hello-ks13] Error 1

**Comment by cahirwpz** [comment]
I reproduced the bug successfully. I must have introduced it lately. Thanks for report.

**Comment by cahirwpz** [comment]
Temporary workaround:

```
$ cd .build-m68k/archives/binutils-2.9.1
$ git reset --hard 309cd5
$ cd -
$ rm -f .build-m68k/stamps/binutils-2.9.1-{configure,unpack,make*}
$ rm -rf .build-m68k/build/binutils-2.9.1
$ ./toolchain-m68k build
$ ./toolchain-m68k test
```

**Comment by OliverUrbann** [comment]
Ok, builds again after I removed a file called include. But hello-iostream still crashes here. Can you reproduce that?

**Comment by cahirwpz** [comment]
Yes. Could you deliver the binary you compiled on Amiga? I'd like to compare both and see where's the difference that causes a crash.

**Comment by OliverUrbann** [comment]
[hello-iostream.zip](https://github.com/cahirwpz/amigaos-cross-toolchain/files/258755/hello-iostream.zip)

I tried to link the example with the libs of my working compiler (btw. it is this one: http://aminet.net/package/dev/gg/GG-Lite-bin-m68k)  with the m68k-amigaos-ld and this also crashes so I expect it is the linker itself. Tell me if you need more (object files etc.)

**Comment by cahirwpz** [comment]
@OliverUrbann Did you compile your `hello-iostream` binary with `-noixemul` option?

**Comment by cahirwpz** [comment]
This is more complicated that I initially thought. It's an issue spanning `libgcc`, `gcc` driver and `libnix`. The cause of crash was related to missing global constructor and destructor handling.
