### ISSUE TITLE
Toolchain compile Error using newest Cygwin 2.874 (32 bit)

### ISSUE THREAD

**Issue by SiENcE** [cahirwpz/amigaos-cross-toolchain#44]
I get an error when building the toolchain under cygwin 2.874 (32 bit).

Attached the console output.

[output.txt](https://github.com/cahirwpz/amigaos-cross-toolchain/files/279399/output.txt)

**Comment by cahirwpz** [comment]
Just built the toolchain with newest Cygwin. No problems whatsoever. 

```
$ uname -a
CYGWIN_NT-6.1 MacBook-PC 2.5.2(0.297/5/3) 2016-06-23 14:27 i686 Cygwin
```
