### ISSUE TITLE
Add SDI headers

### ISSUE THREAD

**Issue by cnvogelg** [cahirwpz/amigaos-cross-toolchain#45]
Hi Krystian,

it would be really great if the SDI headers would be available in os-include as I use them often and have to install them every time I setup a cross toolchain.

The headers can be found here: https://github.com/adtools/SDI

I simply checkout the SDI repo in os-include to have the headers in a SDI sub-folder.

Thanks for considering,
Chris

**Comment by cahirwpz** [comment]
Done.
