### ISSUE TITLE
clean up directory structure for prefix installation

### ISSUE THREAD

**Issue by cmsj** [cahirwpz/amigaos-cross-toolchain#47]
I just noticed that I have an `m68k-amigaos` inside my `/opt/m68k-amigaos` directory. It seems to have a fairly small number of files (ar, as, nm, ld and a few other binaries, plus the os-includes and libnix/clib2 directories).

I'm mildly sure this is wrong, but I wanted to check before I start digging into the build script.

**Comment by cahirwpz** [comment]
This is perfectly ok. For that matter the toolchain installation should have not messed with any prefix structure (including `/usr` or `/opt/local`), but that's not true as for now. What should be done then? Here is a list:

* move `$PREFIX/doc` to `$PREFIX/$TARGET/doc`,
* prevent binutils from installing files into `$PREFIX/include` and `$PREFIX/lib`,
* move `$PREFIX/man` into `$PREFIX/share/man`
* move `$PREFIX/{os,vbcc}-{include,lib}` into `$PREFIX/$TARGET`.
* move `$PREFIX/etc/vc.config` into `$PREFIX/$TARGET` ?

With that being done I'm pretty confident the toolchain would be ready for hassle free inclusion into many Mac / Linux package systems.

Obviously moving the files around isn't enough. Paths are embedded into many binaries and they need to be patched and thoroughly tested to make sure nothing's got broken. That isn't particularly difficult but is time consuming. Is that worth the effort? In long term the answer is yes. Unfortunately I'm quite busy now with some other projects. I'd appreciate if you could help me a bit.

**Comment by cmsj** [comment]
Sorry, I'm slightly confused - what are you meanings for `$PREFIX` and `$TARGET` there? In terms of the toolchain-m68k script, the two are equivalent, right? The user specifies `--prefix=/opt/m68k-amigaos` and internally the script refers to that as `{target}`, if I am reading it correctly?

**Comment by cahirwpz** [comment]
When I referred to `$PREFIX` I meant a `configure` script variable that is set based on argument to `--prefix` option, same for `$TARGET`. I should probably change `{target}` variable to `{prefix}`.

`$PREFIX` is any directory you want to install software into (as with `configure`). `$TARGET` is platform name, in our case `m68k-amigaos`.

**Comment by cahirwpz** [comment]
I cleaned up installation directory structure in [prefix_cleanup](https://github.com/cahirwpz/amigaos-cross-toolchain/tree/prefix_cleanup) branch. It looks like this for the time being. There're still some changes to be done (marked with arrow). 

```
bin/fd2sfd
bin/gg-fix-includes
bin/ira
bin/m68k-amigaos-*
bin/sfdc
bin/vasm
bin/vc
bin/vda68k
bin/vlink
bin/vobjdump
bin/vprof
lib/gcc-lib/m68k-amigaos/2.95.3/*
man/man1/m68k-amigaos-* [->] share/man/man1/m68k-amigaos-*
m68k-amigaos/bin/*
m68k-amigaos/clib2/*
m68k-amigaos/doc/*
m68k-amigaos/info/*
m68k-amigaos/lib/*
m68k-amigaos/libnix/*
m68k-amigaos/sys-include/*
m68k-amigaos/vbcc/*
m68k-amigaos/vc.config [->] etc/vc.config
os-include/* [->] m68k-amigaos/ndk/include/*
os-lib/* [->] m68k-amigaos/ndk/lib/*
share/fd2sfd/*
share/man/man1/sfdc.1
```

Let me know if such directory structure can be installed in Homebrew without causing damage to installation prefix.
