### ISSUE TITLE
add fd2pragma

### ISSUE THREAD

**Issue by cnvogelg** [cahirwpz/amigaos-cross-toolchain#53]
Hi Krystian,

`fd2pragma` would be a very useful addition to your fine set of tools.
In contrast to `sfdc` it allows you to create inline files for VBCC from custom fd files (and lots more :))

Although its initially an Amiga program, the source is available and you can already compile it (with warnings) on your host as a cross tool. 

The most recent source version I found is 2.195 contained in [fd2pragma-mos](http://aminet.net/package/dev/misc/fd2pragma-mos) on aminet.

Additionally, this tool would be a good candidate for the `adtools`git repo...

Best,
Chris

**Comment by cahirwpz** [comment]
Please ask current maintainer (Dirk Stoecker) if he's willing to move development to github. We could try to convince him `adtools` is right place to keep his sources. Current development takes place [here](http://sditools.cvs.sourceforge.net/viewvc/sditools/sditools/fd2pragma/).

**Comment by jens-maus** [comment]
I could move over the fd2pragma sources from sf.net to GitHub within the adtools project, if required. Then we could integrate the MOS changes into that as referenced here.

**Comment by cahirwpz** [comment]
SGTM! Please do so in your free time and I'll integrate it with the toolchain.

**Comment by jens-maus** [comment]
I just recognized that Frank Wille (vbcc author) seems to be still checking in changes to the old sourceforge.net CVS repository where the fd2pragma sources are currently hosted. I first need to check with Frank if it would be fine with hime to move the sources over to GitHub before I will create a new fd2pragma repository there.

**Comment by jens-maus** [comment]
After having talked to Frank Wille he didn't oppose to move the fd2pragma sources to Github. So here you are:

https://github.com/adtools/fd2pragma

**Comment by cahirwpz** [comment]
Done! Please verify!

**Comment by cnvogelg** [comment]
Tested ok. Works like a charm. Thanks!
