### ISSUE TITLE
cybergraphics.h missing 'WritePixelArrayAlpha'

### ISSUE THREAD

**Issue by jens-maus** [cahirwpz/amigaos-cross-toolchain#61]
Latest versions of the cybergraphics.library API also contain a `WritePixelArrayAlpha` function at `0xd8`. The required inlines are however missing in `m68k-amigaos/ndk/include/inline/cybergraphics.h`.

In other versions of the `inline/cybergraphics.h` file `WritePixelArrayAlpha` is defined as:

```
#define WritePixelArrayAlpha(srcRect, SrcX, SrcY, SrcMod, a1arg, DestX, DestY, SizeX, SizeY, AlphaValue) \
    LP10(0xd8, ULONG, WritePixelArrayAlpha, APTR, srcRect, a0, UWORD, SrcX, d0, UWORD, SrcY, d1, UWORD, SrcMod, d2, struct RastPort *, a1arg, a1, UWORD, DestX, d3, UWORD, DestY, d4, UWORD, SizeX, d5, UWORD, SizeY, d6, ULONG, AlphaValue, d7, \
    , CYBERGRAPHICS_BASE_NAME)
```

It would be great if this definition could be added to the cybergraphics.h file your toolchain is installing per default.

**Comment by cahirwpz** [comment]
Such definition is missing in official DevKit available [here](http://aminet.net/dev/misc/CGraphX-DevKit.lha). I'd prefer to fetch more recent version of SDK, rather than patching existing one.

**Comment by jens-maus** [comment]
Well, of course that would be nice, but guess what? This will most certainly never happen (again). The uploaded version on Aminen is from 1998 and chances are almost zero that you will ever see an update on that appearing on AmiNet again. So IMHO it would be good to have some kind of patch set management also for the third party sources in your toolchain that will be applied after having downloaded and unarchived these sources. And if you want you could then add an option like "--omnit-sdk-patches" that omits applying any patches. How about that?
