### ISSUE TITLE
warning: `GetOutlinePen' redefined

### ISSUE THREAD

**Issue by jens-maus** [cahirwpz/amigaos-cross-toolchain#63]
With the default NDK you are installing in your cross toolchain, the following warning occur during compilation of different Amiga projects I am maintaining (MUI, etc.):

```
In file included from /opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/proto/graphics.h:13,
                 from symbols.h:119,
                 from master.h:36,
                 from Area.c:33:
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/inline/graphics.h:576: warning: `GetOutlinePen' redefined
/opt/m68k-amigaos/lib/gcc-lib/m68k-amigaos/2.95.3/../../../../m68k-amigaos/include/../ndk/include/graphics/gfxmacros.h:120: warning: this is the location of the previous definition
```

By looking at the corresponding header files it seems to be viable to actually comment out the GetOutlinePen() define in gfxmacros.h:

```
/* synonym for GetOPen for consistency with SetOutlinePen */
//#define GetOutlinePen(rp) GetOPen(rp)
```

That's in fact what I am doing here to get rid of these warnings.

**Comment by cahirwpz** [comment]
Please prepare pull request with:
```
#ifndef GetOutlinePen
#define GetOutlinePen(rp) GetOPen(rp)
#endif
```
... and test it. Unfortunately, I have to focus on [mimiker](https://github.com/cahirwpz/mimiker) project right now.
