### ISSUE TITLE
ndk/include/inline/layers.h missing LayerOccluded(), HideLayer(), ShowLayer(), SetLayerInfoBounds()

### ISSUE THREAD

**Issue by jens-maus** [cahirwpz/amigaos-cross-toolchain#65]
When compiling certain projects here I identified certain function inline to be missing in the NDK headers (inline/layers.h) your toolchain provides:

```
0xDE - LayerOccluded()
0xE4 - HideLayer()
0xEA - ShowLayer()
0xF0 - SetLayerInfoBounds()
```

Can you  please add these functions to the corresponding fd/sfd file and update the layers.h inline header file?

**Comment by jens-maus** [comment]
Here I added the following defines now to my local copy of layers.h to fix my compile problems:

```
#define LayerOccluded(___layer) \
      LP1(0xde, LONG, LayerOccluded, struct Layer *, ___layer, a0,\
      , LAYERS_BASE_NAME)

#define HideLayer(___layer) \
      LP1(0xe4, LONG, HideLayer, struct Layer *, ___layer, a0,\
      , LAYERS_BASE_NAME)

#define ShowLayer(___layer, ___infront_of) \
      LP2(0xe4, LONG, ShowLayer , struct Layer *, ___layer, a0, struct Layer *, ___infront_of, a1,\
      , LAYERS_BASE_NAME)

#define SetLayerInfoBounds(___layer, ___bounds) \
      LP2(0xf0, LONG, SetLayerInfoBounds , struct Layer *, ___layer, a0, struct Rectangle *, ___bounds, a1,\
      , LAYERS_BASE_NAME)
```

**Comment by cahirwpz** [comment]
Where can I find documentation for those calls ?

**Comment by jens-maus** [comment]
That's a good question I can, however, not answer exactly :)
All I know is that these functions are there and partly used in MUI (e.g. ShowLayer())

**Comment by tboeckel** [comment]
Just get the AmigaOS4 SDK (http://hyperion-entertainment.biz/index.php/downloads?view=files&parent=30). The functions Jens is referring to are part of layers.library V45+.

**Comment by jens-maus** [comment]
Please note that we checked this situation again in our MUI sources and added a `#if defined(__amigaos4__)` accordingly because all these Layer function were anyway just used/available on OS4. So sorry for this inconvenience/confusion. Thus, closing this ticket.
