### ISSUE TITLE
vc.config created with bad permissions

### ISSUE THREAD

**Issue by sezero** [cahirwpz/amigaos-cross-toolchain#71]
{prefix}/etc/vc.config is copied without group and world read permissions,
i.e. 0600 instead of 0644. If the toolchain is created with root user, say
under /opt/m68k-amigaos/, the config file isn't readable by ordinary users
and vc fails with "no config" error, unless the permissions are corrected
manually.

**Comment by cahirwpz** [comment]
Thanks for fixing the problem! I hope you're aware of the fact, that running the script as root is potentially very dangerous and can do real damage to your system.

**Comment by sezero** [comment]
> I hope you're aware of the fact, that running the script as root is potentially
> very dangerous and can do real damage to your system.

Yup.
